### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by nicolagp** [Aura-healthcare/hrv-analysis#28]
the link for the documentation seems to be broken...

**Comment by robinchampseix** [comment]
Hi Nicolas,

Thanks for reporting. Could you just tell me which link are you talking
about ? On which page ?
On the README.md, on my side I think all documentation links are present...

Cheers,
Robin

**Comment by nicolagp** [comment]
The link on the readme was leading to a missing page, works now! Might have been some weird error on my end...
